"""Initial schema

Revision ID: 24b2d2bf5fba
Revises: 
Create Date: 2026-01-07 19:19:30.372057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b2d2bf5fba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_role'), 'roles', ['role'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mongo_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('migrado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mongo_id'), 'users', ['mongo_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dollar_ops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mongo_id', sa.String(length=100), nullable=False),
    sa.Column('migrado', sa.Boolean(), nullable=True),
    sa.Column('dollar_value_peso', sa.Float(), nullable=False),
    sa.Column('dollar_op', sa.Float(), nullable=False),
    sa.Column('total_pesos', sa.Float(), nullable=False),
    sa.Column('dollar_acum', sa.Float(), nullable=False),
    sa.Column('observations', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dollar_ops_mongo_id'), 'dollar_ops', ['mongo_id'], unique=True)
    op.create_table('historical_incomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mongo_id', sa.String(length=100), nullable=False),
    sa.Column('migrado', sa.Boolean(), nullable=True),
    sa.Column('total_amount_income', sa.Float(), nullable=False),
    sa.Column('total_amount_exit', sa.Float(), nullable=False),
    sa.Column('total_amount_dolar_income', sa.Float(), nullable=False),
    sa.Column('total_amount_dolar_exit', sa.Float(), nullable=False),
    sa.Column('total_income_items', sa.Integer(), nullable=False),
    sa.Column('total_exit_items', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=False),
    sa.Column('last_update_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_incomes_mongo_id'), 'historical_incomes', ['mongo_id'], unique=True)
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mongo_id', sa.String(length=100), nullable=False),
    sa.Column('migrado', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_mongo_id'), 'incomes', ['mongo_id'], unique=True)
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_index(op.f('ix_incomes_mongo_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_historical_incomes_mongo_id'), table_name='historical_incomes')
    op.drop_table('historical_incomes')
    op.drop_index(op.f('ix_dollar_ops_mongo_id'), table_name='dollar_ops')
    op.drop_table('dollar_ops')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_mongo_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_role'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
