"""update schema

Revision ID: cff92b33abec
Revises: 24b2d2bf5fba
Create Date: 2026-01-07 21:56:14.422028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cff92b33abec'
down_revision: Union[str, Sequence[str], None] = '24b2d2bf5fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_incomes', sa.Column('total_amount_dollar_income', sa.Float(), nullable=False))
    op.add_column('historical_incomes', sa.Column('total_amount_dollar_exit', sa.Float(), nullable=False))
    op.add_column('historical_incomes', sa.Column('total_amount_dollar_oficial', sa.Float(), nullable=False))
    op.add_column('historical_incomes', sa.Column('total_amount_dollar_free', sa.Float(), nullable=False))
    op.drop_column('historical_incomes', 'total_amount_dolar_income')
    op.drop_column('historical_incomes', 'total_amount_dolar_exit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_incomes', sa.Column('total_amount_dolar_exit', mysql.FLOAT(), nullable=False))
    op.add_column('historical_incomes', sa.Column('total_amount_dolar_income', mysql.FLOAT(), nullable=False))
    op.drop_column('historical_incomes', 'total_amount_dollar_free')
    op.drop_column('historical_incomes', 'total_amount_dollar_oficial')
    op.drop_column('historical_incomes', 'total_amount_dollar_exit')
    op.drop_column('historical_incomes', 'total_amount_dollar_income')
    # ### end Alembic commands ###
